name: Weather App Deploy

on:
  push:
    branches:
      -main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Rebuild Solution
        run: dotnet build --configuration Release
      - name: Turn off web server
        run: Stop-Service W3SVC
      - name: Publish
        run: dotnet publish -o C:/CTC-PCVM/weatherApp/
      - name: Migrate Angular App to Site Directory
        run: Copy-Item -Path "runner\_work\weatherApp\weatherApp\angularwithasp.client\dist\weatherApp.client\browser\" -Destination "C:\CTC-PCVM\weatherApp\wwwroot\" -Recurse
      - name: Start web server
        run: Start-Service W3SVC
