name: Weather App Deploy

on:
  push:
    branches:
      -main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Build Weather Project
        run: dotnet build --configuration Release
      - name: Turn off web server
        run: Stop-Service W3SVC
      - name: Publish Weather API to Server
        run: dotnet publish -o C:/CTC-PCVM/weatherApp/
      - name: Wipe wwwroot
        run: Remove-Item -Path "C:\CTC-PCVM\weatherApp\wwwroot\*" -Recurse -Force
      - name: Migrate Weather App to Site
        run: Copy-Item -Path "C:\actions-runner\_work\weatherApp\weatherApp\angularwithasp.client\dist\weatherApp.client\browser\*" -Destination "C:\CTC-PCVM\weatherApp\wwwroot\" -Recurse -Force
      - name: Start web server
        run: Start-Service W3SVC
